### ISSUE TITLE
TypeScript in 5 minutes

### ISSUE THREAD

**Issue by ysm0622** [typescript-study/TypeScript-Handbook#4]

**Comment by devJang** [comment]
~~했지만 했을때 콤마는 안쓰는게 더 우리나라말로 어순이 좋은 것 같구요
맨 밑에 하단에 사진깨지는데 이전에 제가 실수를 했는지 경로가 안맞나봐요
어디 체크만 해놓으면 될듯해요!!
감사합니다!

**Comment by ysm0622** [comment]
넵 피드백 감사합니다. 사진은 수정했습니다.
